version: "2"

volumes:
  db:
    driver: local

services:
  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "cabinscape"
      POSTGRES_PASSWORD: "cabinscape"
      POSTGRES_DB: "cabinscape"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
